name: ismart_web
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  http: ^1.3.0
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  logger: ^2.5.0
  path: ^1.9.1
  mime: ^1.0.4
  flutter_svg: ^2.1.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  connectivity_plus: ^6.1.3
  pinput: ^5.0.1
  easy_localization: ^3.0.7+1
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  local_session_timeout: ^3.2.0
  encrypt_shared_preferences: ^0.9.9
  sliver_tools: ^0.2.12
  animations: ^2.0.11
  shimmer: ^3.0.0
  fl_chart: ^1.0.0
  device_preview_plus: ^2.3.0
  gap: ^3.0.1
  khalti_checkout_flutter: ^1.0.0-dev.4
  percent_indicator: ^4.2.5
  image_picker: ^1.1.2
  nepali_utils: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/pacific/
    - assets/images/sadasya_sewa/
    - assets/icons/navbar/
    - assets/icons/user_account/
    - assets/icons/user_account/personal/
    - assets/icons/user_account/bank_details/
